[tls]
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/etc/traefik/certificates/cert.pem"
        keyFile = "/etc/traefik/certificates/privkey.pem"

  [[tls.certificates]]
    certFile = "/etc/traefik/certificates/cert.pem"
    keyFile = "/etc/traefik/certificates/privkey.pem"
