[log]

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"
          permanent = false

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.traefik]
  address = ":8081"

[api]
    dashboard = true
    insecure  = true

[providers.file]
    directory = "/etc/traefik/dynamic/"
    watch = true

# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
    prefix           = "traefik"
    exposedByDefault = false

    [providers.consulCatalog.endpoint]
      address = "127.0.0.1:8500"
      scheme  = "http"
